logging.level.root=INFO
logging.level.org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor=DEBUG


spring.application.name=springAI
spring.ai.openai.api-key=${OPENAI_API_KEY}

# 1. sdtio way to load the tools
# spring.ai.mcp.client.stdio.servers-configuration=classpath:mcp-servers-stdio.json

# 2. http sse way and mymcpserver is just random name
spring.ai.mcp.client.sse.connections.mymcpserver.url=http://localhost:8090